
services:
  # БД для сервиса управления заметками
  db_notes:
    # Название контейнера
    container_name: db_notes 
    # Значения переменных окружения
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    # Образ для контейнера который будет скачан из DockerHub
    image: mongo:5.0.25
    # Меняем порт MongoDB в контейнере
    command: mongod --port ${MONGO_PORT}
    # Порты, которые будут использоваться в контейнере
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    # Настройки хранилища данных, необходим для сохранения
    # данных в базе данных при остановке контейнера
    volumes:
       - db_notes_vol:/data/db
    # Объявляем внутренную сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - notes-manager
  
  redis_notes:
    # Название контейнера
    container_name: redis_notes
     # Образ для контейнера который будет скачан из DockerHub
    image: redis:7.2.4
    # Меняем порт Redis в контейнере
    command: --port ${REDIS_PORT}
    # Порты, которые будут использоваться в контейнере
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    # Настройки хранилища данных, необходим для сохранения
    # данных в базе данных при остановке контейнера
    volumes:
      - redis-data:/data
    # Объявляем внутренную сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - notes-manager

  notes:
    container_name: notes
    build: ./notes
    depends_on:
      - db_notes
      - redis_notes
    networks:
      - notes-manager
    ports:
      - ${NOTES_PORT}:${NOTES_PORT}
    environment:
      NOTES_PORT: ${NOTES_PORT}
      JWT_SECRET: ${JWT_SECRET}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      LOG_LEVEL: ${LOG_LEVEL}

  # БД для сервиса управления пользователями 
  db_auth:
    # Название контейнера
    container_name: db_auth
    # Значения переменных окружения
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Образ для контейнера который будет скачан из DockerHub
    image: postgres:15-alpine
    # Порты, которые будут использоваться в контейнере
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    # Меняем порт по умолчанию в Postgres контейнере
    command:
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    # Настройки хранилища данных, необходим для сохранения
    # данных в базе данных при остановке контейнера
    volumes:
      - db_auth_vol:/var/lib/postgresql/data
    # Объявляем внутренную сеть докера, для 
    # передачи данных между контейнерами
    networks:
      - notes-manager

# Конфигурация для хранилища данных
volumes:
  db_notes_vol: {}
  redis-data: {}
  db_auth_vol: {}

# Настройки сетей
networks:
  notes-manager:
    driver: bridge
  